### ISSUE TITLE
Conflicts with 2 plugins using the library

### ISSUE THREAD

**Issue by Mte90** [johnbillion/extended-cpts#155]
```
E_ERROR on 45 row in /home/public_html/wp-content/plugins/glossary-by-codeat/vendor/johnbillion/extended-cpts/functions.php.

Cannot redeclare register_extended_post_type() (previously declared in /home/public_html/wp-content/plugins/best-woocommerce-feed/vendor/johnbillion/extended-cpts/extended-cpts.php:71)
```

A user reported that error with our plugin that create a conflict with the library. Both use composer so I guess the issue are that the file doesn't use `function_exists`.

**Comment by johnbillion** [comment]
Thanks for the report Daniele. I need to decide what to do here, I'm not a fan of supporting plugins that bundle dependencies without handling potential conflicts with other plugins that do the same. It feels to me that this isn't something that should be fixed in every Composer library, rather it should be fixed in the consuming application.

I'll have a think about this.

**Comment by Mte90** [comment]
I agree with you, but I think that the patch is so small that shouldn't break anything.

**Comment by vinkla** [comment]
The fix is actually quite common in frameworks such as [Laravel](https://github.com/laravel/framework/blob/f0e1d78ee461c85020d827236fce2386b7544eaa/src/Illuminate/Support/helpers.php#L10) and [Symfony](https://github.com/symfony/symfony/blob/4537f85963fba75f9ec2aa9a39c048140260f1f9/src/Symfony/Component/VarDumper/Resources/functions/dump.php#L14). Though, I agree this should probably be fixed by the consuming application. It is maybe another example where WordPress combined with Composer falls short.

**Comment by johnbillion** [comment]
I've been thinking about this for a while. I appreciate that you get a fatal if multiple plugins bundle the library, but I'm of the opinion that this is not a problem for the library to solve, it's a problem for the consuming application to solve.

With the release of Extended CPTs 5.0 there will be several breaking changes. The solution proposed in #156 does not consider that two plugins can use two different versions of the library that use two different APIs. It papers over the issue of dependency management but does not actually address it.

If you're going to bundle dependencies in a plugin you need to allow them to work safely alongside other plugins that bundle the same dependencies, either at the same or different versions. A `function_exists()` check isn't enough.

The only thing I can suggest is to try [Mozart](https://github.com/coenjacobs/mozart) although it's unclear whether this handles global functions in addition to classes.

**Comment by Mte90** [comment]
So I will wait for 5.0 but I think that something like CMB does to avoid conflicts can be a solution with various versions.

**Comment by Mte90** [comment]
So I tried with mozart but I am getting errors:

![immagine](https://user-images.githubusercontent.com/403283/137770633-6f9d1f4e-6b48-44c6-b21c-53db24800458.png)

I think that namespace doesn't fix the issue at all as I am using the function that is loaded by the library.
If you don't want to do anything in the library I think that the only thing is to create another package that just wrap this library and not enqueue again like my fork but in this way is more simple to manage.

**Comment by johnbillion** [comment]
I've not yet decided if I'll namespace the currently global `register_extended_post_type()` and `register_extended_taxonomy()` functions. Maybe it's best for everyone if I do.

**Comment by vinkla** [comment]
@johnbillion I'm actually and advocate for keeping the current behaviour. It is more common in the Community. Not putting the helper functions under a namespace. It will require all users to update their code.
